### ISSUE TITLE
feature request: support docker image in arm64

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix-docker#196]
We could reuse Travis CI to integrate arm64 environment to CI

Three steps to support:
- [x] APISIX image in alpine (#197)
- [ ] APISIX image in centos (#201)
- [ ] APISIX dashboard image (need travis CI, #200)
